---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "piaa"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "solve-extract-deployment-config"
  namespace: "piaa"
  labels:
    app: "solve-extract-deployment"
    use: "piaa"
    stage: "solve-extract"
data:
  GOOGLE_COMPUTE_INSTANCE: "1"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "solve-extract-deployment"
  namespace: "piaa"
  labels:
    app: "solve-extract-deployment"
    use: "piaa"
    stage: "solve-extract"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "solve-extract-deployment"
      use: "piaa"
      stage: "solve-extract"
  template:
    metadata:
      labels:
        app: "solve-extract-deployment"
        use: "piaa"
        stage: "solve-extract"
    spec:
      containers:
      - name: "solve-extract-sha256"
        image: "gcr.io/panoptes-survey/solve-extract@sha256:899ed1f8d1ff67e62dceb2c142d199c6cce5b4178f52f8ede9cfc8a9c5125404"
        env:
        - name: "GOOGLE_COMPUTE_INSTANCE"
          valueFrom:
            configMapKeyRef:
              key: "GOOGLE_COMPUTE_INSTANCE"
              name: "solve-extract-deployment-config"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "solve-extract-deployment-hpa"
  namespace: "piaa"
  labels:
    app: "solve-extract-deployment"
    use: "piaa"
    stage: "solve-extract"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "solve-extract-deployment"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
